config/routes.rb
Rails.application.routes.draw do

  post '/posts:user_id:post_id', to: 'posts#like', as: 'like_post'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do 
    post '/sessions/friend/:user_id', to: 'sessions#acceptrequest', as: 'friend_request'
    delete '/sessions/friend/:user_id', to: 'sessions#removefriend', as: 'friend_delete'
    post '/sessions/request/:user_id', to: 'sessions#sendrequest', as: 'send_friend_request'
    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # devise_scope :sessions do
    
  # end

  resources :posts

  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post

    def self.likePost(user_id, post_id)
        if Like.where(user: user_id, post: post_id).exists?
            Like.where(user: User.find(user_id), post: Post.find(post_id)).destroy_all
        else
            Like.create(user: User.find(user_id), post: Post.find(post_id))
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, dependent: :destroy # posts user has made
  has_many :likes, dependent: :destroy # posts user has likes
  has_many :liked_posts, through: :posts, source: :likes # posts user has made that have been liked

  has_many :sentrequests, class_name: 'Friend', dependent: :destroy, foreign_key: :sender
  has_many :recivedrequests, class_name: 'Friend', dependent: :destroy, foreign_key: :recipient

  has_and_belongs_to_many :friends, foreign_key: :pal_id, join_table: :relations, class_name: 'User', dependent: :destroy

  def addFriend(friend)
    friends << friend
    friend.friends << self
  end

  def removeFriend(friend)
    friend.friends.delete(self)
    friends.delete(friend)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  helper_method :getPossibleFriends

  # GET /posts
  # GET /posts.json
  def index
    @posts = (Post.where(user_id: current_user.friends) + current_user.posts).sort_by { |p| p.created_at }.reverse

    @post = current_user.posts.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    Like.likePost(like_post_params[:user_id], like_post_params[:post_id])

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def like_post_params
      params.permit(:user_id, :post_id)
    end

    def getPossibleFriends
      return User.where.not(id: current_user.friends)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

    def acceptrequest
        unless friend_accept_params
            return
        end

        current_user.recivedrequests.find_by(sender: friend_accept_params).destroy
        current_user.addFriend(User.find(friend_accept_params))
        redirect_to root_path
    end

    def sendrequest
        Friend.create(sender: current_user.id, recipient: friend_request_params)
        redirect_to root_path
    end

    def removefriend
        current_user.removeFriend(User.find(friend_accept_params))
    end

    private
    def friend_request_params
        params.require(:user_id)
    end

    def friend_accept_params
        params.require(:user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
    
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
          set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
          session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url
        end
      end
    
      def failure
        redirect_to root_path
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navSignedIn.html.erb
    <nav class='navbar'>
        <div class='navbar-brand'>
          <img src='https://www.theodinproject.com/assets/odin-logo-2d729f16279e9fc3b58ce847eacf07f883bdfc95eb23bb5064ed59d36ef551d6.svg', class='navbar-item'>
        </div>
        <div class='navbar-menu'>
          <div class='navbar-end'>
            <div class='navbar-item'>
              <div class='buttons'>
                <%= button_to current_user.username, edit_user_registration_path, method: :get, class: 'button'%>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'button is-info' %>
              </div>
            </div>
          </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinOdinbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>

    <% if user_signed_in? %>
      <%= render partial: '/layouts/navSignedIn'%>
    <%else%>
      <br />
      <div class='columns is-centered'>
        <div class='column is-half has-text-centered'>
          <img src='https://www.theodinproject.com/assets/odin-logo-2d729f16279e9fc3b58ce847eacf07f883bdfc95eb23bb5064ed59d36ef551d6.svg'>
          <h1 class='title'>The Odin Book</h1>
        </div>
      </div>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/posts/_displayPost.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= post.user.username %></strong>
          <br>
          <%= post.title %>
          <br>
          <%= post.body %>
        </p>
      </div>
      <nav class="level">
          <%= link_to like_post_path(user_id: current_user.id, post_id: post.id), method: :post, class:'level-item' do%>
              <span class='icon'><i class="fa fa-heart"><%= post.likes.count %></i></span>
          <%end%>
      </nav>
    </div>
  </article>
</div>

app/views/posts/_form.html.erb
<div class='box'>
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :title, wrapper: false,label: false, placeholder: 'Title',input_html: {class: 'input'} %><br>
    <%= f.input :body, as: :text, wrapper: false, label: false, placeholder: 'Your Post', input_html: {class: 'input textarea'} %>

    <%= f.button :submit, class: 'button mt-2'%>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class='columns'>
  <div class='column is-one-third'>
    <%= render partial: 'users/profile'%>
  </div>
  <div class='column is-one-third'>
    <%= render partial: 'form' %>

    <h2 class='title'>Your feed:</h2>
    <% @posts.each do |post| %>
      <%= render partial: 'displayPost', locals: {post: post} %>
    <% end %>
  </div>
  <div class='column is-one-third'>
    <%= render partial: 'users/otherUsers'%>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_frienddisplay.html.erb
<div class='box'>
    <%= user.username %> <%= button_to "Unfriend", friend_delete_path(user.id), method: :delete, class: 'button'%>
</div>

app/views/users/_otherUsers.html.erb
<nav class='panel'>
    <p class='panel-heading'>Suggested Users</p>
    <% getPossibleFriends.each do  |u| %>
        <% if u.id == current_user.id %>
            <%next%>
        <%end%>
        <% unless current_user.sentrequests.find_by(recipient: u.id).nil? || current_user.recivedrequests.find_by(sender: u.id).nil? %>
            <%next%>
        <%end%>

        <div class='panel-block has-text-centered'><%= render partial: 'users/userdisplay', locals: {user: u} %></div>
    <%end%>
</nav>

app/views/users/_profile.html.erb
<nav class='panel'>
    <p class='panel-heading'><%= current_user.username %></p>
    <p class='panel-block'>Likes: <%= current_user.liked_posts.count %></p>
</nav>


<nav class='panel'>
    <p class='panel-heading'>Friends: <%= current_user.friends.count %></p><br />
    <% current_user.friends.each do  |u| %>
        <div class='panel-block'><%= u.username %> <%= button_to "Unfriend", friend_delete_path(u.id), method: :delete, class: 'button'%></div>
    <%end%>
</nav>
<nav class='panel'>
    <p class='panel-heading'>Friend Requests</p>
    <% current_user.recivedrequests.each  do |u| %>
        <div class='box'>
            <%= User.find(u.sender).username %> : <%= button_to "Accept Request", friend_request_path(u.sender), class: 'button' %>
        </div>
    <%end%>
</nav>

app/views/users/_userdisplay.html.erb
    <%= user.username %> : 

    <% if current_user.sentrequests.find_by(recipient: user.id).nil? %>
        <%= button_to "Add Friend!", send_friend_request_path(user_id: user.id), class: 'button' %>
    <%else%>
        Request Sent!
    <%end%>